name: flutter_app2
description: A new Flutter application.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  camera: ^0.6.3+2
  path_provider: ^1.6.24

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/images/
